### ISSUE TITLE
Unit tests fail with Couchbase server v5.0.0

### ISSUE THREAD

**Issue by bkdotcom** [matthiasmullie/scrapbook#27]
I'm not a Couchbase guru, so I'm not sure what's going on

`$this->client->manager()->info()`  now returns null....

`$manager->flush()`    doesn't seem to flush?

**Comment by matthiasmullie** [comment]
What version of the Couchbase PHP SDK do you use, and do you use a 'couchbase' or 'memcached' bucket type?

**Comment by matthiasmullie** [comment]
Oh, nevermind, I hadn't properly read the title - the issue is in the tests, so that should be latest release on Docker with 'memcached' bucket type

**Comment by bkdotcom** [comment]
actually...
I'm just running from the command line via 
`phpunit --testsuite scrapbook --group Couchbase`
I don't _think_ docker is utilized

Also:  bucket-type = `couchbase` & flush is enabled

extension version | 2.4.2
libcouchbase runtime version | 2.8.2
libcouchbase headers version | 2.8.2

I'm on OSX
this _may_ be a case of me needing to clear out my ~/Library/Application Support/Couchbase dir after upgrading...  (was required after downgrading back to 4.5.1)

Sorry for the vagueness

**Comment by bkdotcom** [comment]
Unrelated:
I've noticed Couchbase (v4.5.1) to be MUCH slower than the other adapters
`phpunit --testsuite scrapbook --group Couchbase`  (nearly 7 seconds)
vs say
`phpunit --testsuite scrapbook --group PostgreSQL`  (approx 400ms)

not sure if that's a couchbase config issue on my end..

**Comment by matthiasmullie** [comment]
I updated the test suite to work with Couchbase 5.0, but can't reproduce what you are encountering (also with a type=couchbase bucket). Are you still unable to run them?

As for the slowness: I experience that too. I assume setting up the Couchbase connection is slightly slower (I suspect because of the ->info() call), and that keeps being repeated for every test, so that adds up. I'll look into that in more detail, though, to make sure it's not an actual issue of the implementation.

**Comment by matthiasmullie** [comment]
It's Couchbase's flush that is slow (and apparently [always has been](https://forums.couchbase.com/t/flushing-is-very-slow/166/6).)

**Comment by bkdotcom** [comment]
good find.. my search for "couchbase slow" came up empty handed..

> $manager->flush() doesn't seem to flush?

That comment must have been collection related

All is now well
