### ISSUE TITLE
psr6 problems

### ISSUE THREAD

**Issue by leemason** [matthiasmullie/scrapbook#3]
just installed the package, used the default memory store and wrapped it with a psr6 implementation, the tried this:

``` php
$pool = $app->get(\Psr\Cache\CacheItemPoolInterface::class);//aliased to \MatthiasMullie\Scrapbook\Psr6\Pool(\MatthiasMullie\Scrapbook\Adapters\MemoryStore())

        $item = $pool->getItem('widget_list'); // this is all thats needed to cause the error
        if (!$item->isHit()) {
            $value = ['array', 'of', 'values'];
            $item->set($value);
            $pool->save($item);
        }
        return $item->get();
```

this is what i got back:

Fatal Error: Class MatthiasMullie\Scrapbook\Psr6\Item contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Psr\Cache\CacheItemInterface::exists, Psr\Cache\CacheItemInterface::setExpiration) in ...

**Comment by matthiasmullie** [comment]
Hi @leemason, and thanks for the bug report!

Any chance you include an older version of the PSR-6 interfaces? Until recently, Psr\Cache\CacheItemInterface had methods 'exists' and 'setExpiration', but these don't exist anymore (see https://github.com/php-fig/fig-standards/blob/master/proposed/cache.md), so I've also removed them from the PSR-6 implementation.

**Comment by leemason** [comment]
i havent included the psr package at all, its pulling from your composer file "providing" the psr interfaces

**Comment by matthiasmullie** [comment]
Could you post the contents of your composer.lock file? I'n curious what commit scrapbook is at, and if there are any other libraries that may come with a different/older version of PSR-6.

The latter seems most plausible right now, since I only removed these methods from `MatthiasMullie\Scrapbook\Psr6\Item` (5c576d827682ae9ce6a27ca170e2db978847f99b) after I had updated the `Psr\Cache\CacheItemInterface` copies (09dbfcce20d6c025feaff643fe5de739c2b587f0)

**Comment by matthiasmullie** [comment]
PSR-6 is out now & the way PSR-6 interfaces are loaded has changed (no longer included in Scrapbook, but loaded from psr/cache)
